### ISSUE TITLE
GENIUS!!!!!!!!!

### ISSUE THREAD

**Issue by phuang1024** [anish-lakkapragada/GithubStreak#3]
Kento also has a "All you need papers" updated daily.
Also, I don't endorse cheating

**Comment by KentoNishi** [comment]
@phuang1024 But that doesn't count toward the commit streak becuz I commit it using a GitHub actions account AND it also doesn't even commit daily, only when a new paper appears.

**Comment by r2dev2** [comment]
@phuang1024 just time shift some commits so they fall on days you missed I mean wut

**Comment by anish-lakkapragada** [comment]
u'll be able to see my commits, probably not on this repo
